lang: ja
title: ちくわのノート

permalink: /:basename
collections:
  notes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# jekyll-seo-tag

twitter:
  username: chiquwa111
  card: summary

# custom

twitter_username: chiquwa111
github_username: chikuwa111
