lang: ja
title: ちくわのノート

permalink: /:basename
collections:
  notes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"

# minima

theme: minima
minima:
  social_links:
    twitter: chiquwa111
    github: chikuwa111

# jekyll-seo-tag

twitter:
  username: chiquwa111
  card: summary
