include: ['_notes']
lang: ja
title: blog.chikuwa111.com
permalink: pretty

# jekyll-seo-tag

twitter:
  username: chiquwa111
  card: summary

# custom

twitter_username: chiquwa111
github_username: chikuwa111
